-- Gosee — infos pratiques (oct. 2026) : à coller tel quel dans le SQL Editor
-- de Supabase, puis « Run ». Sans risque à relancer (mêmes valeurs).
-- Équivaut à exécuter le bloc « Infos pratiques » de schema.sql + npm run seed,
-- sans avoir besoin d'un PC. Généré depuis data/seed/lieux.json.

begin;

-- Infos pratiques pour les recommandations personnalisées (oct. 2026) :
-- prix lisible (sourcé quand trouvé), gamme/durée/ambiances/public en codes
-- filtrables. infos_estimees = gamme/durée estimées faute de source publique.
alter table lieux add column if not exists prix text;
alter table lieux add column if not exists price_level text check (price_level in
  ('gratuit','economique','moyen','eleve'));
alter table lieux add column if not exists duree text check (duree in
  ('courte','demi_journee','journee','sejour'));
alter table lieux add column if not exists tags text[] not null default '{}';
alter table lieux add column if not exists ideal_pour text[] not null default '{}';
alter table lieux add column if not exists infos_estimees boolean not null default false;

update lieux set prix = 'Entrée libre (lieu de culte)', price_level = 'gratuit', duree = 'courte', tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = false where slug = 'eglise-sainte-rita';
update lieux set prix = 'Entrée gratuite', price_level = 'gratuit', duree = 'courte', tags = array['art','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'fondation-zinsou';
update lieux set prix = 'Accès libre', price_level = 'gratuit', duree = 'courte', tags = array['plage','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = false where slug = 'plage-de-fidjrosse';
update lieux set prix = 'Accès libre (espace public)', price_level = 'gratuit', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'statue-de-l-amazone-place-du-souvenir';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['sport']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'stade-de-l-amitie';
update lieux set prix = 'Parcours en accès libre ; guide en option', price_level = 'gratuit', duree = 'demi_journee', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'route-des-esclaves';
update lieux set prix = '≈ 2 000 FCFA / pers. (tarif relevé en 2021)', price_level = 'economique', duree = 'courte', tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'temple-des-pythons';
update lieux set prix = '≈ 1 100 FCFA / pers. (tarif relevé en 2021)', price_level = 'economique', duree = 'courte', tags = array['spiritualite','nature','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'foret-sacree-de-kpasse';
update lieux set prix = '≈ 5 000 FCFA / pers. pour le musée d''histoire (tarif 2021, fermeture possible)', price_level = 'moyen', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = false where slug = 'fort-portugais-de-ouidah';
update lieux set prix = '≈ 5 000 à 10 500 FCFA / pers. (pirogue + guide, selon taille du groupe)', price_level = 'moyen', duree = 'demi_journee', tags = array['culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'ganvie';
update lieux set prix = '≈ 1 000 FCFA / pers.', price_level = 'economique', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'palais-royal-de-porto-novo';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['histoire','culture','art']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'musee-da-silva';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['culture','art']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'musee-ethnographique-alexandre-senou-adande';
update lieux set prix = 'Visite guidée d''environ 1 h ; restaurant sur place (≈ 1 200 à 3 500 FCFA le plat)', price_level = 'economique', duree = 'courte', tags = array['nature','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'centre-songhai';
update lieux set prix = 'Entrée libre (lieu de culte)', price_level = 'gratuit', duree = 'courte', tags = array['spiritualite','histoire']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = false where slug = 'cathedrale-notre-dame-de-porto-novo';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'cite-royale-de-ketou';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'musee-akaba-idena';
update lieux set prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', tags = array['culture']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = true where slug = 'ville-de-pobe';
update lieux set prix = '≈ 3 000 à 5 000 FCFA / pers.', price_level = 'economique', duree = 'demi_journee', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'palais-royaux-d-abomey';
update lieux set prix = 'Accès libre (espace public)', price_level = 'gratuit', duree = 'courte', tags = array['histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'place-behanzin-place-goho';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'foret-classee-de-la-lama';
update lieux set prix = 'Accès libre (lieu de pèlerinage)', price_level = 'gratuit', duree = 'demi_journee', tags = array['spiritualite','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'grotte-mariale-de-dassa-zoume';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['culture','spiritualite','histoire']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = true where slug = 'savalou-ville-historique-culte-vaudou';
update lieux set prix = 'Accès libre', price_level = 'gratuit', duree = 'demi_journee', tags = array['plage','detente']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'plage-de-grand-popo';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['nature','detente','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'village-de-possotome';
update lieux set prix = '≈ 10 000 FCFA / pers. en pirogue (réductions possibles en groupe)', price_level = 'moyen', duree = 'demi_journee', tags = array['nature','aventure','plage']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'bouche-du-roy';
update lieux set prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', tags = array['culture']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = true where slug = 'ville-de-lokossa';
update lieux set prix = 'Entrée ≈ 19 € adulte étranger, ≈ 7 € résident béninois (anciens tarifs), + véhicule et guide', price_level = 'eleve', duree = 'sejour', tags = array['faune','nature','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'parc-national-de-la-pendjari';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'villages-tata-somba';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['nature','aventure','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = true where slug = 'cascades-de-tanougou';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'musee-regional-de-natitingou';
update lieux set prix = 'Accès libre ; guide conseillé pour la randonnée', price_level = 'gratuit', duree = 'journee', tags = array['nature','aventure','sport']::text[], ideal_pour = array['solo','amis']::text[], infos_estimees = true where slug = 'chaine-de-l-atacora';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis']::text[], infos_estimees = true where slug = 'foret-classee-de-wari-maro';
update lieux set prix = 'Découverte libre', price_level = 'gratuit', duree = 'demi_journee', tags = array['nature','culture']::text[], ideal_pour = array['solo','amis']::text[], infos_estimees = true where slug = 'village-de-bassila';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['culture','art']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'musee-de-plein-air-de-parakou';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'palais-royal-de-nikki';
update lieux set prix = 'Entrée ≈ 10 000 FCFA / 24 h, + véhicule (≈ 60 000 à 70 000 FCFA), guide (≈ 20 000 FCFA) et carburant', price_level = 'eleve', duree = 'sejour', tags = array['faune','nature','aventure']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = false where slug = 'parc-national-du-w';
update lieux set prix = 'Accès libre ; balade en pirogue à négocier sur place', price_level = 'gratuit', duree = 'demi_journee', tags = array['nature','detente']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = true where slug = 'fleuve-niger-rives';
update lieux set prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', tags = array['culture']::text[], ideal_pour = array['solo','amis']::text[], infos_estimees = true where slug = 'ville-de-kandi';
update lieux set prix = 'Dès ≈ 33 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['detente','plage']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = false where slug = 'beach-sand-hotel-resort';
update lieux set prix = 'Dès ≈ 36 € / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = false where slug = 'benin-berge-hotel';
update lieux set prix = 'Dès ≈ 30 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['plage','detente']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = false where slug = 'residences-easy-hotel';
update lieux set prix = null, price_level = 'moyen', duree = 'demi_journee', tags = array['sport','aventure','plage']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'aquamazone';
update lieux set prix = 'Balade libre (transport à prévoir)', price_level = 'gratuit', duree = 'demi_journee', tags = array['plage','detente','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'balade-route-des-peches';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'rio-hotel-ouidah';
update lieux set prix = 'Dès ≈ 127 £ / nuit (plateformes de réservation)', price_level = 'eleve', duree = 'sejour', tags = array['detente','histoire']::text[], ideal_pour = array['couple']::text[], infos_estimees = false where slug = 'native-hotels-ouidah';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente','nature']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = true where slug = 'bel-ami-sur-pilotis';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['loisirs']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'holy-land-parc';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['histoire','culture','spiritualite']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'visite-guidee-de-ouidah-nadal-evasion-tours';
update lieux set prix = '≈ 5 000 à 10 500 FCFA / pers. (pirogue + guide, selon taille du groupe)', price_level = 'moyen', duree = 'demi_journee', tags = array['culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'sortie-pirogue-a-ganvie';
update lieux set prix = 'Dès ≈ 150 USD / nuit (plateformes de réservation)', price_level = 'eleve', duree = 'sejour', tags = array['detente','art']::text[], ideal_pour = array['couple']::text[], infos_estimees = false where slug = 'art-residence-hotel';
update lieux set prix = 'Dès ≈ 44 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = false where slug = 'tour-eiffel-hotel-benin';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['loisirs']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'parc-d-attraction-ife';
update lieux set prix = null, price_level = 'moyen', duree = 'demi_journee', tags = array['nature','aventure','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'balade-sur-la-riviere-noire';
update lieux set prix = 'Entrée libre (achats en sus)', price_level = 'gratuit', duree = 'courte', tags = array['marche','culture']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = false where slug = 'visite-du-grand-marche-de-porto-novo';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'adebayo-hotel';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'visite-du-musee-akaba-idena';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'balade-dans-la-cite-royale-de-ketou';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = true where slug = 'ekagnon-hotel-abomey';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'bois-vert-hotel';
update lieux set prix = '≈ 34 à 73 USD / nuit pour 2 adultes (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['detente','culture']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = false where slug = 'chez-sabine';
update lieux set prix = 'Entrée du site ≈ 3 000 à 5 000 FCFA / pers., guide en sus', price_level = 'economique', duree = 'demi_journee', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'visite-guidee-des-palais-royaux-guide-abomey';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis','famille']::text[], infos_estimees = true where slug = 'decouverte-de-la-foret-classee-de-la-lama';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = true where slug = 'hotel-jeco';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','amis']::text[], infos_estimees = true where slug = 'auberge-de-dassa-zoume';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'loubna-hotel-restauration';
update lieux set prix = 'Accès libre (lieu de pèlerinage)', price_level = 'gratuit', duree = 'demi_journee', tags = array['spiritualite','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'pelerinage-a-la-grotte-mariale-de-dassa';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','amis']::text[], infos_estimees = true where slug = 'visite-du-sanctuaire-vaudou-de-dankoli';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'visite-du-palais-royal-de-savalou';
update lieux set prix = 'Dès ≈ 29 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', tags = array['plage','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = false where slug = 'awale-plage';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['plage','detente']::text[], ideal_pour = array['amis','couple']::text[], infos_estimees = true where slug = 'asva-beach-resort';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['plage','detente']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = true where slug = 'millenium-popo-beach-hotel';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['nature','culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'excursions-avec-bakolo-tours';
update lieux set prix = '≈ 10 000 FCFA / pers. (réductions possibles en groupe)', price_level = 'moyen', duree = 'demi_journee', tags = array['nature','aventure','plage']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'sortie-bateau-vers-la-bouche-du-roy';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'hotel-bellevue';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'hotel-tata-somba';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente','nature']::text[], ideal_pour = array['couple','famille']::text[], infos_estimees = true where slug = 'hotel-totora';
update lieux set prix = 'Entrée ≈ 19 € adulte étranger, ≈ 7 € résident béninois (anciens tarifs), + véhicule et guide', price_level = 'eleve', duree = 'sejour', tags = array['faune','nature','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = false where slug = 'safari-au-parc-national-de-la-pendjari';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'visite-des-villages-tata-somba';
update lieux set prix = null, price_level = 'economique', duree = 'demi_journee', tags = array['nature','aventure','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = true where slug = 'randonnee-aux-cascades-de-tanougou';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','famille']::text[], infos_estimees = true where slug = 'motel-du-lac';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo']::text[], infos_estimees = true where slug = 'hotel-de-la-donga';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo']::text[], infos_estimees = true where slug = 'hotel-cathas';
update lieux set prix = null, price_level = 'moyen', duree = 'journee', tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis']::text[], infos_estimees = true where slug = 'decouverte-de-la-foret-classee-de-wari-maro';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'ola-luxury-hotel';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo','couple','famille']::text[], infos_estimees = true where slug = 'kobourou-city-hotel';
update lieux set prix = null, price_level = 'moyen', duree = 'sejour', tags = array['detente','culture']::text[], ideal_pour = array['solo','couple']::text[], infos_estimees = true where slug = 'hotel-iya-oasis';
update lieux set prix = null, price_level = 'economique', duree = 'courte', tags = array['culture','art']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], infos_estimees = true where slug = 'visite-du-musee-de-plein-air-de-parakou';
update lieux set prix = null, price_level = 'economique', duree = 'sejour', tags = array['detente']::text[], ideal_pour = array['solo']::text[], infos_estimees = true where slug = 'hotel-sejour-du-sahel';
update lieux set prix = 'Entrée ≈ 10 000 FCFA / 24 h, + véhicule (≈ 60 000 à 70 000 FCFA), guide (≈ 20 000 FCFA) et carburant', price_level = 'eleve', duree = 'sejour', tags = array['faune','nature','aventure']::text[], ideal_pour = array['couple','amis','famille']::text[], infos_estimees = false where slug = 'safari-au-parc-national-du-w';

commit;

-- Vérification : doit afficher 90 (lieux remplis) sur 90.
select count(*) filter (where price_level is not null) as lieux_remplis, count(*) as total from lieux;
