-- Gosee — mise à jour du contenu des lieux. GÉNÉRÉ par
-- data/scripts/generate_sql_update.py : ne pas éditer à la main.
-- À coller tel quel dans le SQL Editor de Supabase, puis « Run ».
-- Sans risque à relancer (mêmes valeurs).

begin;

alter table lieux add column if not exists slug text;
alter table lieux add column if not exists website text;
alter table lieux add column if not exists rating numeric(2,1);
alter table lieux add column if not exists reviews_count integer;
alter table lieux add column if not exists prix text;
alter table lieux add column if not exists price_level text check (price_level in
  ('gratuit','economique','moyen','eleve'));
alter table lieux add column if not exists duree text check (duree in
  ('courte','demi_journee','journee','sejour'));
alter table lieux add column if not exists tags text[] not null default '{}';
alter table lieux add column if not exists ideal_pour text[] not null default '{}';
alter table lieux add column if not exists infos_estimees boolean not null default false;
alter table lieux add column if not exists alerte text;
alter table lieux add column if not exists photo_credit text;
alter table lieux add column if not exists photo_source text;

update lieux set description = 'Au cœur du quartier qui porte son nom, l''église Sainte-Rita est l''un des repères les plus connus de Cotonou. On y passe pour une messe, un moment de calme ou simplement pour voir l''animation du carrefour voisin.', horaires = null, contact = null, website = null, prix = 'Entrée libre (lieu de culte)', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'eglise-sainte-rita';
update lieux set description = 'Créée en 2005 par Marie-Cécile Zinsou, la fondation a fait de l''art contemporain africain une sortie gratuite et accessible à tous. Expositions temporaires, médiathèque et ateliers pour enfants : une adresse culturelle incontournable de Cotonou.', horaires = 'Musée principal (Zongo/Haie Vive) : lun 14h-19h, mar-sam 10h-19h, fermé dim. LAB (Fidjrossè) : lun-ven ~9h-18h, fermé dim.', contact = '+229 91 20 70 19', website = 'https://www.fondation-zinsou.org', prix = 'Entrée gratuite', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['art','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'fondation-zinsou';
update lieux set description = 'La plage des Cotonois : sable clair, maquis et paillotes les pieds dans le sable, ambiance animée le week-end. Idéale pour une fin d''après-midi face à l''océan — la baignade y est dangereuse à cause des courants, on profite plutôt du rivage.', horaires = null, contact = null, website = null, prix = 'Accès libre', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'plage-de-fidjrosse';
update lieux set description = 'Inaugurée en 2022, la statue de l''Amazone culmine à près de 30 mètres et rend hommage aux guerrières du royaume du Dahomey. L''esplanade de la Place du Souvenir se prête à une courte visite, idéalement au coucher du soleil.', horaires = null, contact = null, website = null, prix = 'Accès libre (espace public)', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'statue-de-l-amazone-place-du-souvenir';
update lieux set description = 'Le stade Général Mathieu Kérékou, ex-stade de l''Amitié, accueille jusqu''à 35 000 spectateurs. C''est ici que vibrent les grands matchs des Guépards du Bénin et les rassemblements populaires de Cotonou.', horaires = null, contact = '+229 21 38 17 84', website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['sport']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'stade-de-l-amitie';
update lieux set description = 'Un peu plus de trois kilomètres entre la place des enchères et la plage : la Route des Esclaves retrace le dernier chemin des captifs déportés vers les Amériques. L''arbre de l''Oubli, le mémorial de Zoungbodji et la Porte du Non-Retour, érigée en 1995, en marquent les étapes.', horaires = '9h-18h tous les jours', contact = null, website = null, prix = 'Parcours en accès libre ; guide en option', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'route-des-esclaves';
update lieux set description = 'Face à la basilique de l''Immaculée Conception, ce sanctuaire vaudou dédié à Dangbé, le dieu python, abrite des dizaines de pythons royaux. Les guides racontent la place de ces serpents sacrés dans l''histoire de Ouidah — les plus téméraires les portent autour du cou.', horaires = 'Tous les jours, environ 8h-19h', contact = '+229 41 44 87 06', website = null, prix = '≈ 2 000 FCFA / pers. (tarif relevé en 2021)', price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'temple-des-pythons';
update lieux set description = 'Selon la tradition, le roi Kpassè, fondateur de Ouidah, s''y serait changé en iroko pour échapper à ses ennemis. Sous les grands arbres, des sculptures de divinités vaudou installées pour le festival de 1993 jalonnent une balade paisible en plein centre-ville.', horaires = null, contact = null, website = null, prix = '≈ 1 100 FCFA / pers. (tarif relevé en 2021)', price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','nature','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'foret-sacree-de-kpasse';
update lieux set description = 'Construit en 1721, l''ancien fort portugais abrite le musée d''histoire de Ouidah et ses quelque 700 objets sur la traite et les liens entre le Bénin, le Brésil et les Caraïbes. Vérifiez l''ouverture avant de vous déplacer : le site a été annoncé en rénovation.', horaires = null, contact = '+229 21 34 10 21', website = null, prix = '≈ 5 000 FCFA / pers. pour le musée d''histoire (tarif 2021, fermeture possible)', price_level = 'moyen', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'fort-portugais-de-ouidah';
update lieux set description = 'Plus grand village lacustre d''Afrique, Ganvié s''est bâti sur pilotis au milieu du lac Nokoué, où les Tofinu se réfugièrent pour échapper aux razzias esclavagistes. On le découvre en pirogue, entre maisons sur l''eau, marché flottant et techniques de pêche ancestrales.', horaires = null, contact = null, website = null, prix = '≈ 5 000 à 10 500 FCFA / pers. (pirogue + guide, selon taille du groupe)', price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'ganvie';
update lieux set description = 'Le musée Honmè occupe le palais du roi Toffa, qui signa le protectorat avec la France en 1883. Les pièces conservées dans leur état d''origine racontent la vie de cour du royaume de Hogbonou, ancêtre de Porto-Novo.', horaires = null, contact = null, website = null, prix = '≈ 1 000 FCFA / pers.', price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'palais-royal-de-porto-novo';
update lieux set description = 'Installé dans une belle demeure afro-brésilienne de 1870, le musée da Silva retrace l''histoire des Agudas, ces anciens esclaves revenus du Brésil. Mobilier d''époque et photos anciennes font revivre l''architecture et le métissage culturel de Porto-Novo.', horaires = null, contact = '+229 96 53 60 42', website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture','art']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'musee-da-silva';
update lieux set description = 'Fondé en 1957 dans une maison coloniale, le musée Adandé réunit masques guèlèdè, statuettes et objets rituels venus de tout le pays. Une introduction claire à la diversité des cultures béninoises, avant de partir les découvrir sur le terrain.', horaires = null, contact = '+229 20 21 25 54', website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','art']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'musee-ethnographique-alexandre-senou-adande';
update lieux set description = 'Fondé en 1985 par le père Godfrey Nzamujo, Songhaï est devenu une référence de l''agriculture intégrée en Afrique : « rien ne se perd, tout se transforme ». La visite guidée d''une heure parcourt cultures, élevages et ateliers, avant une pause au restaurant ou à la boutique de produits maison.', horaires = 'Visites guidées lun-ven 8h30/10h30/15h30/17h, sam 8h30/10h30/16h', contact = '+229 01 60 93 33 34', website = 'https://songhai.org', prix = 'Visite guidée d''environ 1 h ; restaurant sur place (≈ 1 200 à 3 500 FCFA le plat)', price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'centre-songhai';
update lieux set description = 'La cathédrale Notre-Dame-de-l''Immaculée-Conception affiche une façade colorée inspirée de l''architecture afro-brésilienne du vieux Porto-Novo. Un arrêt rapide pendant une balade dans le centre historique de la capitale.', horaires = 'Messes semaine 6h, 12h45, 18h ; dimanche 7h, 9h, 10h30, 19h', contact = null, website = null, prix = 'Entrée libre (lieu de culte)', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','histoire']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'cathedrale-notre-dame-de-porto-novo';
update lieux set description = 'Kétou, cité yoruba fondée au XIVe siècle, est le berceau du Guèlèdè, inscrit au patrimoine immatériel de l''UNESCO. On y découvre la cour royale, les remparts de terre et la célèbre porte Akaba Idéna.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'cite-royale-de-ketou';
update lieux set description = 'Akaba Idéna, la « porte magique », gardait l''entrée de Kétou ; reconstruite en 1894 après la destruction de la ville par le royaume d''Abomey, elle abrite des autels des divinités yoruba. Le site est en travaux de réhabilitation : renseignez-vous avant de vous déplacer.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'musee-akaba-idena';
update lieux set description = 'Chef-lieu du Plateau, Pobè vit au rythme de la culture yoruba-nago et des palmeraies qui l''entourent. Une étape authentique, loin des circuits classiques, pour qui explore l''est du pays.', horaires = null, contact = null, website = null, prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'ville-de-pobe';
update lieux set description = 'Douze rois du Dahomey se sont succédé ici de 1625 à 1900, chacun bâtissant son propre palais. Classé à l''UNESCO depuis 1985, le site dévoile ses bas-reliefs, trônes et récits de la cour, avec les palais restaurés de Ghézo et de Glèlè.', horaires = 'Tous les jours, 9h-18h', contact = '+229 22 50 03 14', website = null, prix = '≈ 3 000 à 5 000 FCFA / pers.', price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'palais-royaux-d-abomey';
update lieux set description = 'La place Goho rend hommage à Béhanzin, dernier roi du Dahomey indépendant, figure de la résistance à la conquête coloniale. Sa statue monumentale accueille les visiteurs à l''entrée d''Abomey. (Un état d''entretien dégradé a été signalé par la presse locale.)', horaires = null, contact = null, website = null, prix = 'Accès libre (espace public)', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'place-behanzin-place-goho';
update lieux set description = 'Au cœur de ses 16 000 hectares, la forêt de la Lama protège un noyau de forêt dense où vit le singe à ventre rouge, une espèce qu''on ne trouve qu''au Bénin. Une sortie nature à organiser avec un guide, entre Toffo et Zogbodomey.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'foret-classee-de-la-lama';
update lieux set description = 'Nichée dans l''une des 41 collines de Dassa-Zoumé, la grotte Notre-Dame d''Arigbo est le plus grand lieu de pèlerinage du pays depuis 1954. Le week-end du 15 août, des milliers de fidèles y convergent ; le reste de l''année, le site invite au calme.', horaires = 'Ouvert toute l''année ; grand pèlerinage fin août', contact = null, website = null, prix = 'Accès libre (lieu de pèlerinage)', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'grotte-mariale-de-dassa-zoume';
update lieux set description = 'Ancienne capitale du royaume mahi, Savalou mêle palais royal, fêtes de l''igname et cultes vaudou bien vivants. Le célèbre fétiche de Dankoli, à quelques kilomètres, attire des fidèles de toute la région.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','spiritualite','histoire']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'savalou-ville-historique-culte-vaudou';
update lieux set description = 'Entre le fleuve Mono et l''océan, Grand-Popo déroule ses kilomètres de sable bordés de cocotiers, à deux pas du Togo. L''endroit parfait pour décrocher un week-end, entre hôtels de plage et balades en lagune — attention aux courants, la baignade y est risquée.', horaires = null, contact = null, website = null, prix = 'Accès libre', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'plage-de-grand-popo';
update lieux set description = 'Sur la rive du lac Ahémé, Possotomè est célèbre pour sa source thermale, dont l''eau minérale est embouteillée et vendue dans tout le pays. On y vient pour le calme, les balades en pirogue et les villages de pêcheurs alentour.', horaires = null, contact = '+229 95 28 52 20', website = 'https://www.ecobenin.org/possotome', prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','detente','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'village-de-possotome';
update lieux set description = 'Là où le fleuve Mono rejoint l''Atlantique, la Bouche du Roy forme un delta d''îlots, de prairies et de mangroves parmi les mieux préservés du pays. Une excursion en pirogue d''une demi-journée, souvent conclue par des crevettes grillées.', horaires = null, contact = '+229 60 63 08 18', website = 'https://www.boucheduroy.bj', prix = '≈ 10 000 FCFA / pers. en pirogue (réductions possibles en groupe)', price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','aventure','plage']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'bouche-du-roy';
update lieux set description = 'Chef-lieu du Mono, Lokossa est une ville carrefour vivante, point de départ pratique vers le lac Ahémé, Possotomè et la vallée du Mono.', horaires = null, contact = null, website = 'https://lokossa.mairie.bj/fr/decouverte', prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'ville-de-lokossa';
update lieux set description = 'Réserve de biosphère UNESCO depuis 1986, la Pendjari abrite la plus grande population d''éléphants d''Afrique de l''Ouest, ainsi que lions, guépards et hippopotames. Elle forme avec les parcs W et Arly le plus vaste écosystème intact de la région.', horaires = 'Ouvert toute l''année ; safaris recommandés 6h-11h et 16h-tombée de la nuit', contact = null, website = 'https://www.african-parks.org/the-parks/pendjari', prix = 'Entrée ≈ 19 € adulte étranger, ≈ 7 € résident béninois (anciens tarifs), + véhicule et guide', price_level = 'eleve', duree = 'sejour', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['faune','nature','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'parc-national-de-la-pendjari';
update lieux set description = 'Les tata somba, maisons-forteresses en terre à étage des Batammariba, ponctuent les collines entre Natitingou et Boukoumbé. Chaque tata reflète l''organisation familiale et spirituelle de ses habitants : une architecture unique, à découvrir avec un guide local.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'villages-tata-somba';
update lieux set description = 'Au pied de la chaîne de l''Atacora, près de Tanguiéta, la chute de Tanougou plonge d''une quinzaine de mètres dans un bassin naturel propice à la baignade. Le débit varie fortement selon la saison : elle est à son plus beau après les pluies.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = 'Proche des zones frontalières formellement déconseillées du nord. Renseignez-vous sur la situation sécuritaire avant de partir.', photo_credit = null, photo_source = null, tags = array['nature','aventure','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'cascades-de-tanougou';
update lieux set description = 'Dans un bâtiment colonial réhabilité, le musée régional présente l''habitat et les traditions de l''Atacora, avec des maquettes des différents types de tata somba. Le bon point de départ avant d''aller voir les vraies maisons dans les villages.', horaires = 'Lun-Ven 8h30-18h30, Sam-Dim 9h-18h30', contact = '+229 97 88 10 80', website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'musee-regional-de-natitingou';
update lieux set description = 'Le relief le plus marqué du Bénin, qui culmine vers 658 mètres au mont Sokbaro : falaises, vallées et villages perchés pour des randonnées de plusieurs heures. Un guide local est vivement conseillé.', horaires = null, contact = null, website = null, prix = 'Accès libre ; guide conseillé pour la randonnée', price_level = 'gratuit', duree = 'journee', alerte = 'Proche des zones frontalières formellement déconseillées du nord. Renseignez-vous sur la situation sécuritaire avant de partir.', photo_credit = null, photo_source = null, tags = array['nature','aventure','sport']::text[], ideal_pour = array['solo','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'chaine-de-l-atacora';
update lieux set description = 'Plus de 100 000 hectares de forêts sèches, savanes et galeries forestières entre Bassila et Tchaourou, refuge de primates, d''antilopes et parfois du léopard. Une destination nature encore très sauvage, à explorer accompagné. (Statut en évolution : fusion annoncée avec la forêt des Monts Kouffé en un nouveau parc national (déc. gouvernementale nov. 2025).)', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'foret-classee-de-wari-maro';
update lieux set description = 'Commune forestière du sud de la Donga, Bassila sert de porte d''entrée vers la forêt de Wari-Maro et les paysages verdoyants du centre-ouest du pays.', horaires = null, contact = '+229 23 30 11 76', website = null, prix = 'Découverte libre', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','culture']::text[], ideal_pour = array['solo','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'village-de-bassila';
update lieux set description = 'À ciel ouvert, ce musée ethnographique fait découvrir l''habitat traditionnel, les objets et les arts du nord du Bénin. Une visite courte et vivante au cœur de Parakou, la grande ville du Borgou.', horaires = 'Tous les jours 9h-12h et 15h-18h30, sauf jours fériés', contact = '+229 23 61 05 78', website = 'https://tourisme.parakou.bj/2024/01/18/musee-plein-air-et-ethnographique/', prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','art']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'musee-de-plein-air-de-parakou';
update lieux set description = 'Capitale historique des Baatonu (Bariba), Nikki accueille chaque année la Gaani, grande fête identitaire où cavaliers et dignitaires défilent devant le palais royal. Le reste du temps, la cour raconte l''histoire d''un royaume de cavaliers.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'palais-royal-de-nikki';
update lieux set description = 'Partagé entre le Bénin, le Niger et le Burkina Faso et classé à l''UNESCO, le parc W doit son nom aux méandres du fleuve Niger. Éléphants, buffles, hippopotames et oiseaux d''eau y peuplent savanes et zones humides.', horaires = 'Ouvert toute l''année', contact = null, website = null, prix = 'Entrée ≈ 10 000 FCFA / 24 h, + véhicule (≈ 60 000 à 70 000 FCFA), guide (≈ 20 000 FCFA) et carburant', price_level = 'eleve', duree = 'sejour', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['faune','nature','aventure']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'parc-national-du-w';
update lieux set description = 'À Malanville, le fleuve Niger marque la frontière avec le Niger : rizières, pirogues et grand marché transfrontalier rythment la vie des rives. Un paysage sahélien, très différent du sud du pays.', horaires = null, contact = null, website = null, prix = 'Accès libre ; balade en pirogue à négocier sur place', price_level = 'gratuit', duree = 'demi_journee', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['nature','detente']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'fleuve-niger-rives';
update lieux set description = 'Chef-lieu de l''Alibori, Kandi est une ville du nord sahélien, carrefour d''élevage et de commerce sur la route du Niger.', horaires = null, contact = null, website = null, prix = 'Découverte libre de la ville', price_level = 'gratuit', duree = 'demi_journee', alerte = 'Proche des zones frontalières formellement déconseillées du nord. Renseignez-vous sur la situation sécuritaire avant de partir.', photo_credit = null, photo_source = null, tags = array['culture']::text[], ideal_pour = array['solo','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'ville-de-kandi';
update lieux set description = 'Dans le quartier des Ambassades, à quelques pas de la mer, un hôtel bien noté pour séjourner à Cotonou au calme tout en restant proche du centre.', horaires = null, contact = '+229 53 64 91 65', website = 'https://www.beachsandhotel.com', prix = 'Dès ≈ 33 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','plage']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'beach-sand-hotel-resort';
update lieux set description = 'Un hôtel central et sans chichis, pratique pour rayonner dans Cotonou à prix raisonnable.', horaires = null, contact = null, website = null, prix = 'Dès ≈ 36 € / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'benin-berge-hotel';
update lieux set description = 'Un hôtel avec accès direct à la plage, à Cotonou. Les avis en ligne sont très partagés selon les plateformes : regardez les commentaires récents avant de réserver.', horaires = null, contact = '+229 95 21 40 40', website = 'https://easyhotelsbenin.com', prix = 'Dès ≈ 30 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'residences-easy-hotel';
update lieux set description = 'Une base nautique sur la Route des Pêches : kayak, jet-ski et activités en famille, à quelques minutes de Cotonou. De quoi passer une journée active entre lagune et océan.', horaires = null, contact = '+229 01 54 28 44 44', website = 'https://sites.google.com/view/aquamazone229/accueil', prix = null, price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['sport','aventure','plage']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'aquamazone';
update lieux set description = 'Entre Cotonou et Ouidah, la Route des Pêches longe l''océan sur une quarantaine de kilomètres : villages de pêcheurs, cocoteraies, plages et maquis. À parcourir en voiture, à moto ou à vélo, en s''arrêtant au gré des envies.', horaires = null, contact = null, website = null, prix = 'Balade libre (transport à prévoir)', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'balade-route-des-peches';
update lieux set description = 'Un hôtel calme à proximité du centre historique, pratique pour visiter Ouidah à pied.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'rio-hotel-ouidah';
update lieux set description = 'Dans le quartier historique, un petit hôtel de charme de 14 chambres avec piscine, bibliothèque et bar, installé dans des bâtiments coloniaux réhabilités. L''adresse haut de gamme de Ouidah.', horaires = null, contact = '+229 01 45 46 42 88', website = 'https://nativehotels.net', prix = 'Dès ≈ 127 £ / nuit (plateformes de réservation)', price_level = 'eleve', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','histoire']::text[], ideal_pour = array['couple']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'native-hotels-ouidah';
update lieux set description = 'Un hébergement paisible au bord du lac Ahémé, côté Kpomassè : nuits au calme, vue sur l''eau et balades en pirogue au départ de l''hôtel.', horaires = null, contact = '+229 96 18 21 94', website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','nature']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'bel-ami-sur-pilotis';
update lieux set description = 'À Abomey-Calavi, un parc de détente et de loisirs pour souffler le temps d''un après-midi, en famille ou entre amis.', horaires = 'Tous les jours 9h-22h', contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['loisirs']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'holy-land-parc';
update lieux set description = 'Une agence locale qui fait découvrir Ouidah autrement : histoire de la traite, temples et cérémonies vaudou, artisanat. Le guide adapte le circuit à votre temps et à vos centres d''intérêt.', horaires = '24h/24, 7j/7', contact = '+229 01 66 04 40 12', website = 'https://nadalevasiontours.com', prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture','spiritualite']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-guidee-de-ouidah-nadal-evasion-tours';
update lieux set description = 'Au départ de l''embarcadère d''Abomey-Calavi, une pirogue à moteur ou à perche vous emmène à travers le lac Nokoué jusqu''à Ganvié. Comptez deux à quatre heures avec guide, tarif à négocier selon la taille du groupe.', horaires = null, contact = '+229 96 74 06 13', website = 'https://www.visit-ganvie-tourism.com', prix = '≈ 5 000 à 10 500 FCFA / pers. (pirogue + guide, selon taille du groupe)', price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'sortie-pirogue-a-ganvie';
update lieux set description = 'Un hôtel-boutique moderne à Porto-Novo, au décor soigné : l''adresse confortable pour découvrir la capitale.', horaires = null, contact = null, website = 'https://artresidence.bj', prix = 'Dès ≈ 150 USD / nuit (plateformes de réservation)', price_level = 'eleve', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','art']::text[], ideal_pour = array['couple']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'art-residence-hotel';
update lieux set description = 'Grand hôtel de Porto-Novo avec piscine et restaurant, apprécié pour son rapport qualité-prix.', horaires = null, contact = '+229 65 00 38 65', website = null, prix = 'Dès ≈ 44 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'tour-eiffel-hotel-benin';
update lieux set description = 'À Porto-Novo, un parc récréatif où les enfants se dépensent pendant que les parents profitent de l''ombre.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['loisirs']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'parc-d-attraction-ife';
update lieux set description = 'À Adjarra, à quelques kilomètres de Porto-Novo, une pirogue glisse sur la Rivière Noire sous les grands arbres, parmi poissons, reptiles et crocodiles nains. La sortie se termine souvent au marché des tam-tams, fabriqués par les artisans du village.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','aventure','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'balade-sur-la-riviere-noire';
update lieux set description = 'Reconstruit et inauguré en 2026, le grand marché de Ouando s''étend sur 3,5 hectares : tissus, épices, produits frais et artisanat. Plus animé le mercredi et le samedi matin.', horaires = 'Marché quotidien, plus animé mercredi et samedi matin', contact = null, website = null, prix = 'Entrée libre (achats en sus)', price_level = 'gratuit', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['marche','culture']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'visite-du-grand-marche-de-porto-novo';
update lieux set description = 'L''un des hôtels les mieux notés de Pobè, avec restaurant : une halte pratique pour explorer le Plateau.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'adebayo-hotel';
update lieux set description = 'Avec un guide, on découvre l''histoire de Kétou à travers la porte Akaba Idéna et ses légendes de protection magique. Le musée est en cours de réhabilitation : vérifiez l''accès avant de partir.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-du-musee-akaba-idena';
update lieux set description = 'Une immersion dans la plus ancienne cité yoruba du pays : cour royale, remparts, autels et, avec un peu de chance, une sortie de masques guèlèdè.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'balade-dans-la-cite-royale-de-ketou';
update lieux set description = 'L''un des hôtels les mieux notés d''Abomey, idéal pour une nuit confortable après la visite des palais royaux.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'ekagnon-hotel-abomey';
update lieux set description = 'Un hôtel confortable proche du centre d''Abomey, bien placé pour enchaîner palais royaux et marché.', horaires = null, contact = '+229 01 55 40 98 78', website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'bois-vert-hotel';
update lieux set description = 'Une maison d''hôtes chaleureuse à Abomey, où l''on est reçu comme en famille : l''adresse idéale pour découvrir la ville au rythme local.', horaires = null, contact = '+229 63 13 64 64', website = null, prix = '≈ 34 à 73 USD / nuit pour 2 adultes (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','culture']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'chez-sabine';
update lieux set description = 'Un guide local fait revivre les douze rois du Dahomey, leurs palais, leurs bas-reliefs et les récits de la cour. Indispensable pour comprendre ce que l''on voit à Abomey.', horaires = '9h-18h (une source indique 8h-17h)', contact = null, website = null, prix = 'Entrée du site ≈ 3 000 à 5 000 FCFA / pers., guide en sus', price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'visite-guidee-des-palais-royaux-guide-abomey';
update lieux set description = 'Avec un guide, partez à la recherche du singe à ventre rouge, endémique du Bénin, dans le noyau de forêt dense de la Lama. Prévoyez de bonnes chaussures et un départ tôt le matin.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'decouverte-de-la-foret-classee-de-la-lama';
update lieux set description = 'Un grand hôtel de plus de 100 chambres à Dassa-Zoumé, avec piscine, spa et restaurant : la halte confortable sur la route du nord.', horaires = null, contact = '+229 22 53 08 89', website = 'https://jecohotels.com', prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-jeco';
update lieux set description = 'Une auberge simple et bien située, l''étape pratique pour couper le long trajet entre le sud et le nord du pays.', horaires = null, contact = '+229 94 47 21 35', website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'auberge-de-dassa-zoume';
update lieux set description = 'Un hôtel confortable à Paouignan, au pied des collines, avec restaurant sur place. (Référencé en ligne sous le nom « Hôtel Loubna Évolution ».)', horaires = null, contact = null, website = 'https://loubna-hotel.com', prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'loubna-hotel-restauration';
update lieux set description = 'Pèlerinage ou simple visite, la grotte d''Arigbo invite au recueillement au milieu des collines de Dassa. Le grand rassemblement a lieu le week-end du 15 août.', horaires = 'Site ouvert toute l''année ; pèlerinage vers le 15 août', contact = null, website = null, prix = 'Accès libre (lieu de pèlerinage)', price_level = 'gratuit', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','nature']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'pelerinage-a-la-grotte-mariale-de-dassa';
update lieux set description = 'Près de Savalou, le fétiche de Dankoli est l''un des sanctuaires vaudou les plus fréquentés d''Afrique de l''Ouest : on y plante un bout de bois pour formuler un vœu, et l''on revient remercier s''il est exaucé. Une visite forte, à faire avec respect.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['spiritualite','culture']::text[], ideal_pour = array['solo','couple','amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-du-sanctuaire-vaudou-de-dankoli';
update lieux set description = 'Le palais royal de Savalou raconte l''histoire du royaume mahi et de ses souverains. Une visite courte, à combiner avec Dankoli et le centre de la ville.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['histoire','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-du-palais-royal-de-savalou';
update lieux set description = 'Hôtel-restaurant les pieds dans le sable à Grand-Popo, avec bungalows et vue sur l''océan : l''adresse détente du littoral ouest.', horaires = null, contact = '+229 58 01 01 12', website = 'https://www.hotel-benin-awaleplage.com', prix = 'Dès ≈ 29 USD / nuit (plateformes de réservation)', price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'awale-plage';
update lieux set description = 'Proche de la plage de Grand-Popo, un hôtel à l''ambiance festive, apprécié des groupes d''amis.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['amis','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'asva-beach-resort';
update lieux set description = 'Un grand complexe hôtelier en bord de mer à Grand-Popo, avec piscine et accès direct à la plage.', horaires = null, contact = '+229 6860 1111', website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['plage','detente']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'millenium-popo-beach-hotel';
update lieux set description = 'Agence locale de Grand-Popo pour des circuits sur mesure : Bouche du Roy, villages de la lagune, lac Ahémé ou cultes vaudou.', horaires = null, contact = '+229 94 69 96 89', website = 'https://www.bakolotours.com', prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','culture','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'excursions-avec-bakolo-tours';
update lieux set description = 'Une remontée de la lagune d''environ deux heures jusqu''à l''embouchure du Mono, entre mangroves et îlots, avant une pause sur une île de pêcheurs.', horaires = null, contact = null, website = null, prix = '≈ 10 000 FCFA / pers. (réductions possibles en groupe)', price_level = 'moyen', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','aventure','plage']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'sortie-bateau-vers-la-bouche-du-roy';
update lieux set description = 'Un hôtel historique et chaleureux de Natitingou, connu aussi pour son restaurant.', horaires = null, contact = '+229 23 82 13 36', website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-bellevue';
update lieux set description = 'Rénové et rouvert en 2024, l''hôtel Tata Somba est le grand hôtel public du nord, au pied des collines de l''Atacora, avec 25 chambres climatisées.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','culture']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-tata-somba';
update lieux set description = 'Un hôtel avec piscine et vue sur les montagnes de l''Atacora, pour se reposer entre deux excursions au départ de Natitingou.', horaires = null, contact = '+229 62 23 62 52', website = 'https://www.hoteltotora.com', prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','nature']::text[], ideal_pour = array['couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-totora';
update lieux set description = 'Safari guidé à l''aube ou en fin de journée, quand les animaux sont les plus actifs : éléphants, lions, hippopotames et antilopes de la savane soudanienne.', horaires = 'Créneaux recommandés 6h-11h et 16h-tombée de la nuit', contact = null, website = 'https://www.african-parks.org/the-parks/pendjari', prix = 'Entrée ≈ 19 € adulte étranger, ≈ 7 € résident béninois (anciens tarifs), + véhicule et guide', price_level = 'eleve', duree = 'sejour', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['faune','nature','aventure']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'safari-au-parc-national-de-la-pendjari';
update lieux set description = 'Un guide de la région vous ouvre les portes des tata somba et explique la vie en famille dans ces maisons-forteresses à étage, entre greniers, autels et terrasses.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','histoire']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-des-villages-tata-somba';
update lieux set description = 'Une courte marche dans la végétation mène au bassin de la cascade, pour une baignade rafraîchissante au pied de l''Atacora.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'demi_journee', alerte = 'Proche des zones frontalières formellement déconseillées du nord. Renseignez-vous sur la situation sécuritaire avant de partir.', photo_credit = null, photo_source = null, tags = array['nature','aventure','detente']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'randonnee-aux-cascades-de-tanougou';
update lieux set description = 'Un hôtel familial de Djougou, réputé pour sa cuisine.', horaires = null, contact = '+229 97 54 06 56', website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'motel-du-lac';
update lieux set description = 'Un hôtel simple et pratique pour une nuit à Djougou.', horaires = null, contact = '+229 23 80 15 72', website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-de-la-donga';
update lieux set description = 'Un hôtel abordable au centre de Djougou, proche des commerces.', horaires = null, contact = '+229 66 03 37 51', website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-cathas';
update lieux set description = 'Randonnée accompagnée dans l''une des plus vastes forêts classées du pays, à l''affût des primates, des antilopes et des oiseaux.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'journee', alerte = null, photo_credit = null, photo_source = null, tags = array['nature','faune','aventure']::text[], ideal_pour = array['amis']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'decouverte-de-la-foret-classee-de-wari-maro';
update lieux set description = 'Un hôtel confortable et bien noté à Parakou, pour une étape soignée dans le nord.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'ola-luxury-hotel';
update lieux set description = 'Grand hôtel avec piscine à Parakou, pratique pour les séjours en famille comme pour les déplacements professionnels.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo','couple','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'kobourou-city-hotel';
update lieux set description = 'Un hôtel au décor traditionnel, parmi les mieux notés de Parakou, qui offre une vraie touche locale.', horaires = null, contact = null, website = null, prix = null, price_level = 'moyen', duree = 'sejour', alerte = null, photo_credit = null, photo_source = null, tags = array['detente','culture']::text[], ideal_pour = array['solo','couple']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-iya-oasis';
update lieux set description = 'Visite guidée des habitats et objets traditionnels du nord du Bénin, à ciel ouvert, au cœur de Parakou.', horaires = 'Tous les jours 9h-12h et 15h-18h30, sauf jours fériés', contact = '+229 23 61 05 78', website = 'https://tourisme.parakou.bj/2024/01/18/musee-plein-air-et-ethnographique/', prix = null, price_level = 'economique', duree = 'courte', alerte = null, photo_credit = null, photo_source = null, tags = array['culture','art']::text[], ideal_pour = array['solo','couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'visite-du-musee-de-plein-air-de-parakou';
update lieux set description = 'Un hôtel propre et sécurisé à Malanville, près de la frontière avec le Niger.', horaires = null, contact = null, website = null, prix = null, price_level = 'economique', duree = 'sejour', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['detente']::text[], ideal_pour = array['solo']::text[], photos = '{}'::text[], infos_estimees = true, updated_at = now() where slug = 'hotel-sejour-du-sahel';
update lieux set description = 'Observation de la faune du parc W, entre savanes et méandres du fleuve Niger : éléphants, buffles, hippopotames et oiseaux d''eau.', horaires = 'Créneaux recommandés 6h-11h et 16h-tombée de la nuit', contact = null, website = null, prix = 'Entrée ≈ 10 000 FCFA / 24 h, + véhicule (≈ 60 000 à 70 000 FCFA), guide (≈ 20 000 FCFA) et carburant', price_level = 'eleve', duree = 'sejour', alerte = 'Zone formellement déconseillée aux voyageurs (risque d''attaques terroristes et d''enlèvements, frontière nord). Vérifiez les conseils aux voyageurs de votre pays avant tout déplacement.', photo_credit = null, photo_source = null, tags = array['faune','nature','aventure']::text[], ideal_pour = array['couple','amis','famille']::text[], photos = '{}'::text[], infos_estimees = false, updated_at = now() where slug = 'safari-au-parc-national-du-w';

commit;

-- Vérification : lieux_a_jour doit valoir 90.
select count(*) filter (where updated_at > now() - interval '5 minutes') as lieux_a_jour,
       count(*) filter (where alerte is not null) as lieux_en_alerte, count(*) as total from lieux;
